### ISSUE TITLE
When Resleeving from Backup, which if any Resleeving Tests do Infomorphs do?

### ISSUE THREAD

**Issue by itteerde** [itteerde/ep2eRules#4]
When `Resleeving` (pg. 288) from `Backup` (pg. 286), which if any `Resleeving Tests` (pg. 288) do `Infomorphs` (pg. 252) do?

**Comment by itteerde** [comment]
**Resleeving** (pg. 288)
> Resleeving — also called downloading or remorphing — is the process where your ego takes on a new physical body. You may be switching because you want a new morph or because you are egocasting to a new destination; this transfer is usually a smooth transition from one sleeve to the next while conscious.

So (as they have no physical body) I think now that the whole `Resleeving` should never be used for `Informorph`. I do think it should all/only be `Willpower Stress Test` (pg. 229), usually for `Continuity` reasons.

see
- #1

**Comment by PhDaveMil** [comment]
Your paragraph appears to be the rare case of poor word choice on the part of the designers. First it says, "Resleeving--also called downloading or remorphing--is the process where your ego takes on a new physical body" (288). The section then concludes, just a few lines later, "The resleeving process is quite short for morphs with cyberbrains and infomorphs: a single action turn" (288). This means that despite their talk of physical bodies, they clearly imagine that infomorphs do sometimes need to resleeve. Likewise, the rules clearly indicate that when changing your type of infomorph, say a Digimorph to an Ikon, you must resleeve. In other locations, the setting describes the reason why traveling from one device to another device doesn't cause one to resleeve as being a factor of two machines slowly dividing your consciousness between them with no part of you ever being fully off--this includes the egocasting process. While rebooting is specifically called out as something that avoids the resleeving process--I guess it is too short to truly cause it, and perhaps it keeps the original process suspended in a manner similar to Microsoft Word keeping the last document I was working on open when I restart my computer--death is, in other places, a status that is clearly attributed to infomorphs, and death is a status condition that the game is ubiquitously static about: it forces a resleeving test.

After reading what the EP2e player community generally has to say, my ruling is as follows: when you must reinstantiate  yourself from a backup, you must perform a resleeving test. That means that if someone kills you in mesh combat--you, not your shell--you must resleeve. When something destroys your home device, you must resleeve. If you choose to put yourself in storage as a backup and get spun up again at a later date, you must resleeve. All those events count as "switching your physical body," perhaps because every process must be instatiated on a physical medium, and spinning up an infomorph from cold storage onto a new piece of hardware without going through the "A to B slow copy and then delete" process described in the book counts as receiving a new physical body (in the form of a new piece of hardware on which your infomorph is now run).

**Comment by itteerde** [comment]
> The resleeving process is quite short for morphs with cyberbrains and infomorphs: a single action turn

Oh, that settles it for if there are any. As they then do not differenciate I guess the default case has to apply and both are.
